#!/bin/bash
#SBATCH -J gnn
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --gres=gpu:1
#SBATCH --time=1:00:00
#SBATCH --output=./.slurm/%A/%a_output.log
#SBATCH --error=./.slurm/%A/%a_error.log
#SBATCH --mem=64g
#SBATCH --array=0-27
slurm_dir=./.slurm/$SLURM_ARRAY_JOB_ID
mkdir -p $slurm_dir
echo Creating directory: $slurm_dir
nvidia-smi
module load rust gcc arrow
. .env/bin/activate
declare -a cmd_list=(
# 'python3 ./src/train.py --opts --results_suffix 62454355/68 --seed 2 --use_gnn_steps 0 --gnn_layers 0 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
# 'python3 ./src/train.py --opts --results_suffix 62454355/46 --seed 1 --use_gnn_steps 0 --gnn_layers 1 --parser_type gat --top_k 4 --arc_norm 1 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
# 'python3 ./src/train.py --opts --results_suffix 62454355/26 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
# 'python3 ./src/train.py --opts --results_suffix 62454355/12 --seed 0 --use_gnn_steps 0 --gnn_layers 1 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
# 'python3 ./src/train.py --opts --results_suffix 62454355/20 --seed 0 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
# 'python3 ./src/train.py --opts --results_suffix 62454355/43 --seed 1 --use_gnn_steps 0 --gnn_layers 1 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
# 'python3 ./src/train.py --opts --results_suffix 62454355/64 --seed 2 --use_gnn_steps 0 --gnn_layers 0 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/19 --seed 0 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/57 --seed 1 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/15 --seed 0 --use_gnn_steps 0 --gnn_layers 1 --parser_type gat --top_k 4 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/49 --seed 1 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/10 --seed 0 --use_gnn_steps 0 --gnn_layers 1 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/29 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/30 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 4 --arc_norm 1 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/61 --seed 1 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/31 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 4 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/25 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/33 --seed 1 --use_gnn_steps 0 --gnn_layers 0 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/23 --seed 0 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 4 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/59 --seed 1 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/24 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/55 --seed 1 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 4 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/27 --seed 0 --use_gnn_steps 0 --gnn_layers 3 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/65 --seed 2 --use_gnn_steps 0 --gnn_layers 0 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/42 --seed 1 --use_gnn_steps 0 --gnn_layers 1 --parser_type gat --top_k 1 --arc_norm 1 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/17 --seed 0 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 1 --arc_norm 0 --gnn_dropout 0.3 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/52 --seed 1 --use_gnn_steps 0 --gnn_layers 2 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
'python3 ./src/train.py --opts --results_suffix 62454355/36 --seed 1 --use_gnn_steps 0 --gnn_layers 0 --parser_type gat --top_k 4 --arc_norm 0 --gnn_dropout 0 --gnn_activation tanh --dataset scidtb --training_steps 10000 --eval_steps 500 --use_tagger_rnn 0 --use_parser_rnn 0 --parser_rnn_hidden_size 400 --parser_rnn_layers 0 --use_pred_tags 0'
)

echo ${cmd_list[${SLURM_ARRAY_TASK_ID}]}

${cmd_list[${SLURM_ARRAY_TASK_ID}]}